//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fpWebApp.WSRedeban {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSRedeban.SIPServiceSoap")]
    public interface SIPServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VersionResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Version", ReplyAction="*")]
        fpWebApp.WSRedeban.VersionResponse Version(fpWebApp.WSRedeban.VersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Version", ReplyAction="*")]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.VersionResponse> VersionAsync(fpWebApp.WSRedeban.VersionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cod_Unico del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatosCompra", ReplyAction="*")]
        fpWebApp.WSRedeban.DatosCompraResponse DatosCompra(fpWebApp.WSRedeban.DatosCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatosCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.DatosCompraResponse> DatosCompraAsync(fpWebApp.WSRedeban.DatosCompraRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cod_Unico del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatosAnulacionJSON", ReplyAction="*")]
        fpWebApp.WSRedeban.DatosAnulacionJSONResponse DatosAnulacionJSON(fpWebApp.WSRedeban.DatosAnulacionJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatosAnulacionJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.DatosAnulacionJSONResponse> DatosAnulacionJSONAsync(fpWebApp.WSRedeban.DatosAnulacionJSONRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cod_Unico del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatosCompraJSON", ReplyAction="*")]
        fpWebApp.WSRedeban.DatosCompraJSONResponse DatosCompraJSON(fpWebApp.WSRedeban.DatosCompraJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatosCompraJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.DatosCompraJSONResponse> DatosCompraJSONAsync(fpWebApp.WSRedeban.DatosCompraJSONRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cod_Unico del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatosAnulacion", ReplyAction="*")]
        fpWebApp.WSRedeban.DatosAnulacionResponse DatosAnulacion(fpWebApp.WSRedeban.DatosAnulacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatosAnulacion", ReplyAction="*")]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.DatosAnulacionResponse> DatosAnulacionAsync(fpWebApp.WSRedeban.DatosAnulacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cod_unico del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Token", ReplyAction="*")]
        fpWebApp.WSRedeban.TokenResponse Token(fpWebApp.WSRedeban.TokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Token", ReplyAction="*")]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.TokenResponse> TokenAsync(fpWebApp.WSRedeban.TokenRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cod_unico del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Respuesta", ReplyAction="*")]
        fpWebApp.WSRedeban.RespuestaResponse Respuesta(fpWebApp.WSRedeban.RespuestaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Respuesta", ReplyAction="*")]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.RespuestaResponse> RespuestaAsync(fpWebApp.WSRedeban.RespuestaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cod_unico del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RespuestaJSON", ReplyAction="*")]
        fpWebApp.WSRedeban.RespuestaJSONResponse RespuestaJSON(fpWebApp.WSRedeban.RespuestaJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RespuestaJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.RespuestaJSONResponse> RespuestaJSONAsync(fpWebApp.WSRedeban.RespuestaJSONRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cod_unico del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarTransaccion", ReplyAction="*")]
        fpWebApp.WSRedeban.BorrarTransaccionResponse BorrarTransaccion(fpWebApp.WSRedeban.BorrarTransaccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarTransaccion", ReplyAction="*")]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.BorrarTransaccionResponse> BorrarTransaccionAsync(fpWebApp.WSRedeban.BorrarTransaccionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cod_unico del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarTransaccionJSON", ReplyAction="*")]
        fpWebApp.WSRedeban.BorrarTransaccionJSONResponse BorrarTransaccionJSON(fpWebApp.WSRedeban.BorrarTransaccionJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarTransaccionJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.BorrarTransaccionJSONResponse> BorrarTransaccionJSONAsync(fpWebApp.WSRedeban.BorrarTransaccionJSONRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Version", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.VersionRequestBody Body;
        
        public VersionRequest() {
        }
        
        public VersionRequest(fpWebApp.WSRedeban.VersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VersionRequestBody {
        
        public VersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.VersionResponseBody Body;
        
        public VersionResponse() {
        }
        
        public VersionResponse(fpWebApp.WSRedeban.VersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VersionResult;
        
        public VersionResponseBody() {
        }
        
        public VersionResponseBody(string VersionResult) {
            this.VersionResult = VersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatosCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatosCompra", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.DatosCompraRequestBody Body;
        
        public DatosCompraRequest() {
        }
        
        public DatosCompraRequest(fpWebApp.WSRedeban.DatosCompraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatosCompraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cod_Unico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id_transaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sobreescribir;
        
        public DatosCompraRequestBody() {
        }
        
        public DatosCompraRequestBody(string Cod_Unico, string id_transaccion, string Data, string token, string sobreescribir) {
            this.Cod_Unico = Cod_Unico;
            this.id_transaccion = id_transaccion;
            this.Data = Data;
            this.token = token;
            this.sobreescribir = sobreescribir;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatosCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatosCompraResponse", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.DatosCompraResponseBody Body;
        
        public DatosCompraResponse() {
        }
        
        public DatosCompraResponse(fpWebApp.WSRedeban.DatosCompraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatosCompraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DatosCompraResult;
        
        public DatosCompraResponseBody() {
        }
        
        public DatosCompraResponseBody(string DatosCompraResult) {
            this.DatosCompraResult = DatosCompraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatosAnulacionJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatosAnulacionJSON", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.DatosAnulacionJSONRequestBody Body;
        
        public DatosAnulacionJSONRequest() {
        }
        
        public DatosAnulacionJSONRequest(fpWebApp.WSRedeban.DatosAnulacionJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatosAnulacionJSONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cod_Unico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id_transaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sobreescribir;
        
        public DatosAnulacionJSONRequestBody() {
        }
        
        public DatosAnulacionJSONRequestBody(string Cod_Unico, string id_transaccion, string Data, string token, string sobreescribir) {
            this.Cod_Unico = Cod_Unico;
            this.id_transaccion = id_transaccion;
            this.Data = Data;
            this.token = token;
            this.sobreescribir = sobreescribir;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatosAnulacionJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatosAnulacionJSONResponse", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.DatosAnulacionJSONResponseBody Body;
        
        public DatosAnulacionJSONResponse() {
        }
        
        public DatosAnulacionJSONResponse(fpWebApp.WSRedeban.DatosAnulacionJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatosAnulacionJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DatosAnulacionJSONResult;
        
        public DatosAnulacionJSONResponseBody() {
        }
        
        public DatosAnulacionJSONResponseBody(string DatosAnulacionJSONResult) {
            this.DatosAnulacionJSONResult = DatosAnulacionJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatosCompraJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatosCompraJSON", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.DatosCompraJSONRequestBody Body;
        
        public DatosCompraJSONRequest() {
        }
        
        public DatosCompraJSONRequest(fpWebApp.WSRedeban.DatosCompraJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatosCompraJSONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cod_Unico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id_transaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sobreescribir;
        
        public DatosCompraJSONRequestBody() {
        }
        
        public DatosCompraJSONRequestBody(string Cod_Unico, string id_transaccion, string Data, string token, string sobreescribir) {
            this.Cod_Unico = Cod_Unico;
            this.id_transaccion = id_transaccion;
            this.Data = Data;
            this.token = token;
            this.sobreescribir = sobreescribir;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatosCompraJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatosCompraJSONResponse", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.DatosCompraJSONResponseBody Body;
        
        public DatosCompraJSONResponse() {
        }
        
        public DatosCompraJSONResponse(fpWebApp.WSRedeban.DatosCompraJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatosCompraJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DatosCompraJSONResult;
        
        public DatosCompraJSONResponseBody() {
        }
        
        public DatosCompraJSONResponseBody(string DatosCompraJSONResult) {
            this.DatosCompraJSONResult = DatosCompraJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatosAnulacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatosAnulacion", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.DatosAnulacionRequestBody Body;
        
        public DatosAnulacionRequest() {
        }
        
        public DatosAnulacionRequest(fpWebApp.WSRedeban.DatosAnulacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatosAnulacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cod_Unico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id_transaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sobreescribir;
        
        public DatosAnulacionRequestBody() {
        }
        
        public DatosAnulacionRequestBody(string Cod_Unico, string id_transaccion, string Data, string token, string sobreescribir) {
            this.Cod_Unico = Cod_Unico;
            this.id_transaccion = id_transaccion;
            this.Data = Data;
            this.token = token;
            this.sobreescribir = sobreescribir;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DatosAnulacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DatosAnulacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.DatosAnulacionResponseBody Body;
        
        public DatosAnulacionResponse() {
        }
        
        public DatosAnulacionResponse(fpWebApp.WSRedeban.DatosAnulacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DatosAnulacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DatosAnulacionResult;
        
        public DatosAnulacionResponseBody() {
        }
        
        public DatosAnulacionResponseBody(string DatosAnulacionResult) {
            this.DatosAnulacionResult = DatosAnulacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Token", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.TokenRequestBody Body;
        
        public TokenRequest() {
        }
        
        public TokenRequest(fpWebApp.WSRedeban.TokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cod_unico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string clave;
        
        public TokenRequestBody() {
        }
        
        public TokenRequestBody(string Cod_unico, string usuario, string clave) {
            this.Cod_unico = Cod_unico;
            this.usuario = usuario;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.TokenResponseBody Body;
        
        public TokenResponse() {
        }
        
        public TokenResponse(fpWebApp.WSRedeban.TokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenResult;
        
        public TokenResponseBody() {
        }
        
        public TokenResponseBody(string TokenResult) {
            this.TokenResult = TokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RespuestaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Respuesta", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.RespuestaRequestBody Body;
        
        public RespuestaRequest() {
        }
        
        public RespuestaRequest(fpWebApp.WSRedeban.RespuestaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cod_unico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id_transaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        public RespuestaRequestBody() {
        }
        
        public RespuestaRequestBody(string Cod_unico, string id_transaccion, string token) {
            this.Cod_unico = Cod_unico;
            this.id_transaccion = id_transaccion;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RespuestaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RespuestaResponse", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.RespuestaResponseBody Body;
        
        public RespuestaResponse() {
        }
        
        public RespuestaResponse(fpWebApp.WSRedeban.RespuestaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RespuestaResult;
        
        public RespuestaResponseBody() {
        }
        
        public RespuestaResponseBody(string RespuestaResult) {
            this.RespuestaResult = RespuestaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RespuestaJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RespuestaJSON", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.RespuestaJSONRequestBody Body;
        
        public RespuestaJSONRequest() {
        }
        
        public RespuestaJSONRequest(fpWebApp.WSRedeban.RespuestaJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestaJSONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cod_unico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id_transaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        public RespuestaJSONRequestBody() {
        }
        
        public RespuestaJSONRequestBody(string Cod_unico, string id_transaccion, string token) {
            this.Cod_unico = Cod_unico;
            this.id_transaccion = id_transaccion;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RespuestaJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RespuestaJSONResponse", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.RespuestaJSONResponseBody Body;
        
        public RespuestaJSONResponse() {
        }
        
        public RespuestaJSONResponse(fpWebApp.WSRedeban.RespuestaJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestaJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RespuestaJSONResult;
        
        public RespuestaJSONResponseBody() {
        }
        
        public RespuestaJSONResponseBody(string RespuestaJSONResult) {
            this.RespuestaJSONResult = RespuestaJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorrarTransaccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BorrarTransaccion", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.BorrarTransaccionRequestBody Body;
        
        public BorrarTransaccionRequest() {
        }
        
        public BorrarTransaccionRequest(fpWebApp.WSRedeban.BorrarTransaccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BorrarTransaccionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cod_unico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id_transaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        public BorrarTransaccionRequestBody() {
        }
        
        public BorrarTransaccionRequestBody(string Cod_unico, string id_transaccion, string token) {
            this.Cod_unico = Cod_unico;
            this.id_transaccion = id_transaccion;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorrarTransaccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BorrarTransaccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.BorrarTransaccionResponseBody Body;
        
        public BorrarTransaccionResponse() {
        }
        
        public BorrarTransaccionResponse(fpWebApp.WSRedeban.BorrarTransaccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BorrarTransaccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BorrarTransaccionResult;
        
        public BorrarTransaccionResponseBody() {
        }
        
        public BorrarTransaccionResponseBody(string BorrarTransaccionResult) {
            this.BorrarTransaccionResult = BorrarTransaccionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorrarTransaccionJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BorrarTransaccionJSON", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.BorrarTransaccionJSONRequestBody Body;
        
        public BorrarTransaccionJSONRequest() {
        }
        
        public BorrarTransaccionJSONRequest(fpWebApp.WSRedeban.BorrarTransaccionJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BorrarTransaccionJSONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Cod_unico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id_transaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        public BorrarTransaccionJSONRequestBody() {
        }
        
        public BorrarTransaccionJSONRequestBody(string Cod_unico, string id_transaccion, string token) {
            this.Cod_unico = Cod_unico;
            this.id_transaccion = id_transaccion;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorrarTransaccionJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BorrarTransaccionJSONResponse", Namespace="http://tempuri.org/", Order=0)]
        public fpWebApp.WSRedeban.BorrarTransaccionJSONResponseBody Body;
        
        public BorrarTransaccionJSONResponse() {
        }
        
        public BorrarTransaccionJSONResponse(fpWebApp.WSRedeban.BorrarTransaccionJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BorrarTransaccionJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BorrarTransaccionJSONResult;
        
        public BorrarTransaccionJSONResponseBody() {
        }
        
        public BorrarTransaccionJSONResponseBody(string BorrarTransaccionJSONResult) {
            this.BorrarTransaccionJSONResult = BorrarTransaccionJSONResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SIPServiceSoapChannel : fpWebApp.WSRedeban.SIPServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SIPServiceSoapClient : System.ServiceModel.ClientBase<fpWebApp.WSRedeban.SIPServiceSoap>, fpWebApp.WSRedeban.SIPServiceSoap {
        
        public SIPServiceSoapClient() {
        }
        
        public SIPServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SIPServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SIPServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SIPServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fpWebApp.WSRedeban.VersionResponse fpWebApp.WSRedeban.SIPServiceSoap.Version(fpWebApp.WSRedeban.VersionRequest request) {
            return base.Channel.Version(request);
        }
        
        public string Version() {
            fpWebApp.WSRedeban.VersionRequest inValue = new fpWebApp.WSRedeban.VersionRequest();
            inValue.Body = new fpWebApp.WSRedeban.VersionRequestBody();
            fpWebApp.WSRedeban.VersionResponse retVal = ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).Version(inValue);
            return retVal.Body.VersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.VersionResponse> fpWebApp.WSRedeban.SIPServiceSoap.VersionAsync(fpWebApp.WSRedeban.VersionRequest request) {
            return base.Channel.VersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<fpWebApp.WSRedeban.VersionResponse> VersionAsync() {
            fpWebApp.WSRedeban.VersionRequest inValue = new fpWebApp.WSRedeban.VersionRequest();
            inValue.Body = new fpWebApp.WSRedeban.VersionRequestBody();
            return ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).VersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fpWebApp.WSRedeban.DatosCompraResponse fpWebApp.WSRedeban.SIPServiceSoap.DatosCompra(fpWebApp.WSRedeban.DatosCompraRequest request) {
            return base.Channel.DatosCompra(request);
        }
        
        public string DatosCompra(string Cod_Unico, string id_transaccion, string Data, string token, string sobreescribir) {
            fpWebApp.WSRedeban.DatosCompraRequest inValue = new fpWebApp.WSRedeban.DatosCompraRequest();
            inValue.Body = new fpWebApp.WSRedeban.DatosCompraRequestBody();
            inValue.Body.Cod_Unico = Cod_Unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.Data = Data;
            inValue.Body.token = token;
            inValue.Body.sobreescribir = sobreescribir;
            fpWebApp.WSRedeban.DatosCompraResponse retVal = ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).DatosCompra(inValue);
            return retVal.Body.DatosCompraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.DatosCompraResponse> fpWebApp.WSRedeban.SIPServiceSoap.DatosCompraAsync(fpWebApp.WSRedeban.DatosCompraRequest request) {
            return base.Channel.DatosCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<fpWebApp.WSRedeban.DatosCompraResponse> DatosCompraAsync(string Cod_Unico, string id_transaccion, string Data, string token, string sobreescribir) {
            fpWebApp.WSRedeban.DatosCompraRequest inValue = new fpWebApp.WSRedeban.DatosCompraRequest();
            inValue.Body = new fpWebApp.WSRedeban.DatosCompraRequestBody();
            inValue.Body.Cod_Unico = Cod_Unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.Data = Data;
            inValue.Body.token = token;
            inValue.Body.sobreescribir = sobreescribir;
            return ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).DatosCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fpWebApp.WSRedeban.DatosAnulacionJSONResponse fpWebApp.WSRedeban.SIPServiceSoap.DatosAnulacionJSON(fpWebApp.WSRedeban.DatosAnulacionJSONRequest request) {
            return base.Channel.DatosAnulacionJSON(request);
        }
        
        public string DatosAnulacionJSON(string Cod_Unico, string id_transaccion, string Data, string token, string sobreescribir) {
            fpWebApp.WSRedeban.DatosAnulacionJSONRequest inValue = new fpWebApp.WSRedeban.DatosAnulacionJSONRequest();
            inValue.Body = new fpWebApp.WSRedeban.DatosAnulacionJSONRequestBody();
            inValue.Body.Cod_Unico = Cod_Unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.Data = Data;
            inValue.Body.token = token;
            inValue.Body.sobreescribir = sobreescribir;
            fpWebApp.WSRedeban.DatosAnulacionJSONResponse retVal = ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).DatosAnulacionJSON(inValue);
            return retVal.Body.DatosAnulacionJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.DatosAnulacionJSONResponse> fpWebApp.WSRedeban.SIPServiceSoap.DatosAnulacionJSONAsync(fpWebApp.WSRedeban.DatosAnulacionJSONRequest request) {
            return base.Channel.DatosAnulacionJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<fpWebApp.WSRedeban.DatosAnulacionJSONResponse> DatosAnulacionJSONAsync(string Cod_Unico, string id_transaccion, string Data, string token, string sobreescribir) {
            fpWebApp.WSRedeban.DatosAnulacionJSONRequest inValue = new fpWebApp.WSRedeban.DatosAnulacionJSONRequest();
            inValue.Body = new fpWebApp.WSRedeban.DatosAnulacionJSONRequestBody();
            inValue.Body.Cod_Unico = Cod_Unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.Data = Data;
            inValue.Body.token = token;
            inValue.Body.sobreescribir = sobreescribir;
            return ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).DatosAnulacionJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fpWebApp.WSRedeban.DatosCompraJSONResponse fpWebApp.WSRedeban.SIPServiceSoap.DatosCompraJSON(fpWebApp.WSRedeban.DatosCompraJSONRequest request) {
            return base.Channel.DatosCompraJSON(request);
        }
        
        public string DatosCompraJSON(string Cod_Unico, string id_transaccion, string Data, string token, string sobreescribir) {
            fpWebApp.WSRedeban.DatosCompraJSONRequest inValue = new fpWebApp.WSRedeban.DatosCompraJSONRequest();
            inValue.Body = new fpWebApp.WSRedeban.DatosCompraJSONRequestBody();
            inValue.Body.Cod_Unico = Cod_Unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.Data = Data;
            inValue.Body.token = token;
            inValue.Body.sobreescribir = sobreescribir;
            fpWebApp.WSRedeban.DatosCompraJSONResponse retVal = ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).DatosCompraJSON(inValue);
            return retVal.Body.DatosCompraJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.DatosCompraJSONResponse> fpWebApp.WSRedeban.SIPServiceSoap.DatosCompraJSONAsync(fpWebApp.WSRedeban.DatosCompraJSONRequest request) {
            return base.Channel.DatosCompraJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<fpWebApp.WSRedeban.DatosCompraJSONResponse> DatosCompraJSONAsync(string Cod_Unico, string id_transaccion, string Data, string token, string sobreescribir) {
            fpWebApp.WSRedeban.DatosCompraJSONRequest inValue = new fpWebApp.WSRedeban.DatosCompraJSONRequest();
            inValue.Body = new fpWebApp.WSRedeban.DatosCompraJSONRequestBody();
            inValue.Body.Cod_Unico = Cod_Unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.Data = Data;
            inValue.Body.token = token;
            inValue.Body.sobreescribir = sobreescribir;
            return ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).DatosCompraJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fpWebApp.WSRedeban.DatosAnulacionResponse fpWebApp.WSRedeban.SIPServiceSoap.DatosAnulacion(fpWebApp.WSRedeban.DatosAnulacionRequest request) {
            return base.Channel.DatosAnulacion(request);
        }
        
        public string DatosAnulacion(string Cod_Unico, string id_transaccion, string Data, string token, string sobreescribir) {
            fpWebApp.WSRedeban.DatosAnulacionRequest inValue = new fpWebApp.WSRedeban.DatosAnulacionRequest();
            inValue.Body = new fpWebApp.WSRedeban.DatosAnulacionRequestBody();
            inValue.Body.Cod_Unico = Cod_Unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.Data = Data;
            inValue.Body.token = token;
            inValue.Body.sobreescribir = sobreescribir;
            fpWebApp.WSRedeban.DatosAnulacionResponse retVal = ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).DatosAnulacion(inValue);
            return retVal.Body.DatosAnulacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.DatosAnulacionResponse> fpWebApp.WSRedeban.SIPServiceSoap.DatosAnulacionAsync(fpWebApp.WSRedeban.DatosAnulacionRequest request) {
            return base.Channel.DatosAnulacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<fpWebApp.WSRedeban.DatosAnulacionResponse> DatosAnulacionAsync(string Cod_Unico, string id_transaccion, string Data, string token, string sobreescribir) {
            fpWebApp.WSRedeban.DatosAnulacionRequest inValue = new fpWebApp.WSRedeban.DatosAnulacionRequest();
            inValue.Body = new fpWebApp.WSRedeban.DatosAnulacionRequestBody();
            inValue.Body.Cod_Unico = Cod_Unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.Data = Data;
            inValue.Body.token = token;
            inValue.Body.sobreescribir = sobreescribir;
            return ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).DatosAnulacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fpWebApp.WSRedeban.TokenResponse fpWebApp.WSRedeban.SIPServiceSoap.Token(fpWebApp.WSRedeban.TokenRequest request) {
            return base.Channel.Token(request);
        }
        
        public string Token(string Cod_unico, string usuario, string clave) {
            fpWebApp.WSRedeban.TokenRequest inValue = new fpWebApp.WSRedeban.TokenRequest();
            inValue.Body = new fpWebApp.WSRedeban.TokenRequestBody();
            inValue.Body.Cod_unico = Cod_unico;
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            fpWebApp.WSRedeban.TokenResponse retVal = ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).Token(inValue);
            return retVal.Body.TokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.TokenResponse> fpWebApp.WSRedeban.SIPServiceSoap.TokenAsync(fpWebApp.WSRedeban.TokenRequest request) {
            return base.Channel.TokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<fpWebApp.WSRedeban.TokenResponse> TokenAsync(string Cod_unico, string usuario, string clave) {
            fpWebApp.WSRedeban.TokenRequest inValue = new fpWebApp.WSRedeban.TokenRequest();
            inValue.Body = new fpWebApp.WSRedeban.TokenRequestBody();
            inValue.Body.Cod_unico = Cod_unico;
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            return ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).TokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fpWebApp.WSRedeban.RespuestaResponse fpWebApp.WSRedeban.SIPServiceSoap.Respuesta(fpWebApp.WSRedeban.RespuestaRequest request) {
            return base.Channel.Respuesta(request);
        }
        
        public string Respuesta(string Cod_unico, string id_transaccion, string token) {
            fpWebApp.WSRedeban.RespuestaRequest inValue = new fpWebApp.WSRedeban.RespuestaRequest();
            inValue.Body = new fpWebApp.WSRedeban.RespuestaRequestBody();
            inValue.Body.Cod_unico = Cod_unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.token = token;
            fpWebApp.WSRedeban.RespuestaResponse retVal = ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).Respuesta(inValue);
            return retVal.Body.RespuestaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.RespuestaResponse> fpWebApp.WSRedeban.SIPServiceSoap.RespuestaAsync(fpWebApp.WSRedeban.RespuestaRequest request) {
            return base.Channel.RespuestaAsync(request);
        }
        
        public System.Threading.Tasks.Task<fpWebApp.WSRedeban.RespuestaResponse> RespuestaAsync(string Cod_unico, string id_transaccion, string token) {
            fpWebApp.WSRedeban.RespuestaRequest inValue = new fpWebApp.WSRedeban.RespuestaRequest();
            inValue.Body = new fpWebApp.WSRedeban.RespuestaRequestBody();
            inValue.Body.Cod_unico = Cod_unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.token = token;
            return ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).RespuestaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fpWebApp.WSRedeban.RespuestaJSONResponse fpWebApp.WSRedeban.SIPServiceSoap.RespuestaJSON(fpWebApp.WSRedeban.RespuestaJSONRequest request) {
            return base.Channel.RespuestaJSON(request);
        }
        
        public string RespuestaJSON(string Cod_unico, string id_transaccion, string token) {
            fpWebApp.WSRedeban.RespuestaJSONRequest inValue = new fpWebApp.WSRedeban.RespuestaJSONRequest();
            inValue.Body = new fpWebApp.WSRedeban.RespuestaJSONRequestBody();
            inValue.Body.Cod_unico = Cod_unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.token = token;
            fpWebApp.WSRedeban.RespuestaJSONResponse retVal = ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).RespuestaJSON(inValue);
            return retVal.Body.RespuestaJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.RespuestaJSONResponse> fpWebApp.WSRedeban.SIPServiceSoap.RespuestaJSONAsync(fpWebApp.WSRedeban.RespuestaJSONRequest request) {
            return base.Channel.RespuestaJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<fpWebApp.WSRedeban.RespuestaJSONResponse> RespuestaJSONAsync(string Cod_unico, string id_transaccion, string token) {
            fpWebApp.WSRedeban.RespuestaJSONRequest inValue = new fpWebApp.WSRedeban.RespuestaJSONRequest();
            inValue.Body = new fpWebApp.WSRedeban.RespuestaJSONRequestBody();
            inValue.Body.Cod_unico = Cod_unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.token = token;
            return ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).RespuestaJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fpWebApp.WSRedeban.BorrarTransaccionResponse fpWebApp.WSRedeban.SIPServiceSoap.BorrarTransaccion(fpWebApp.WSRedeban.BorrarTransaccionRequest request) {
            return base.Channel.BorrarTransaccion(request);
        }
        
        public string BorrarTransaccion(string Cod_unico, string id_transaccion, string token) {
            fpWebApp.WSRedeban.BorrarTransaccionRequest inValue = new fpWebApp.WSRedeban.BorrarTransaccionRequest();
            inValue.Body = new fpWebApp.WSRedeban.BorrarTransaccionRequestBody();
            inValue.Body.Cod_unico = Cod_unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.token = token;
            fpWebApp.WSRedeban.BorrarTransaccionResponse retVal = ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).BorrarTransaccion(inValue);
            return retVal.Body.BorrarTransaccionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.BorrarTransaccionResponse> fpWebApp.WSRedeban.SIPServiceSoap.BorrarTransaccionAsync(fpWebApp.WSRedeban.BorrarTransaccionRequest request) {
            return base.Channel.BorrarTransaccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<fpWebApp.WSRedeban.BorrarTransaccionResponse> BorrarTransaccionAsync(string Cod_unico, string id_transaccion, string token) {
            fpWebApp.WSRedeban.BorrarTransaccionRequest inValue = new fpWebApp.WSRedeban.BorrarTransaccionRequest();
            inValue.Body = new fpWebApp.WSRedeban.BorrarTransaccionRequestBody();
            inValue.Body.Cod_unico = Cod_unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.token = token;
            return ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).BorrarTransaccionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        fpWebApp.WSRedeban.BorrarTransaccionJSONResponse fpWebApp.WSRedeban.SIPServiceSoap.BorrarTransaccionJSON(fpWebApp.WSRedeban.BorrarTransaccionJSONRequest request) {
            return base.Channel.BorrarTransaccionJSON(request);
        }
        
        public string BorrarTransaccionJSON(string Cod_unico, string id_transaccion, string token) {
            fpWebApp.WSRedeban.BorrarTransaccionJSONRequest inValue = new fpWebApp.WSRedeban.BorrarTransaccionJSONRequest();
            inValue.Body = new fpWebApp.WSRedeban.BorrarTransaccionJSONRequestBody();
            inValue.Body.Cod_unico = Cod_unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.token = token;
            fpWebApp.WSRedeban.BorrarTransaccionJSONResponse retVal = ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).BorrarTransaccionJSON(inValue);
            return retVal.Body.BorrarTransaccionJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<fpWebApp.WSRedeban.BorrarTransaccionJSONResponse> fpWebApp.WSRedeban.SIPServiceSoap.BorrarTransaccionJSONAsync(fpWebApp.WSRedeban.BorrarTransaccionJSONRequest request) {
            return base.Channel.BorrarTransaccionJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<fpWebApp.WSRedeban.BorrarTransaccionJSONResponse> BorrarTransaccionJSONAsync(string Cod_unico, string id_transaccion, string token) {
            fpWebApp.WSRedeban.BorrarTransaccionJSONRequest inValue = new fpWebApp.WSRedeban.BorrarTransaccionJSONRequest();
            inValue.Body = new fpWebApp.WSRedeban.BorrarTransaccionJSONRequestBody();
            inValue.Body.Cod_unico = Cod_unico;
            inValue.Body.id_transaccion = id_transaccion;
            inValue.Body.token = token;
            return ((fpWebApp.WSRedeban.SIPServiceSoap)(this)).BorrarTransaccionJSONAsync(inValue);
        }
    }
}
